### ISSUE TITLE
<samp> is used incorrectly

### ISSUE THREAD

**Issue by chris-morgan** [andybrewer/mvp#1]
`<samp>` is an inline element with particular semantics. It should not be used for block preformatted text, because otherwise it will appear quite incorrectly if mvp.css doesn’t load. (Quite apart from any differences screen readers might perceive—I’m not sure if there are any.)

Use `<pre>` for block preformatted text instead, ideally supporting `<pre><code>…</code></pre>` and `<pre><samp>…</samp></pre>` also for optimal semantic nuance.

**Comment by philp** [comment]
Inclined to agree here. Even though you might have semantic HTML, styling any element within a `<p>` as `display: block` is still considered semantically incorrect.

Nothing wrong with `<p><samp>...</samp></p>` though, which gives you best of both worlds!

**Comment by andybrewer** [comment]
Thanks @chris-morgan ! This was a tricky one for me to decide on and I saw different articles recommending different approaches. I think I was trying to be too clever in ditching the `<pre>` tag. I'll make a fix in the next version.

**Comment by DennisSuitters** [comment]
Love Mozilla myself, have you checked what W3C says about the `<samp/>` element?
https://www.w3.org/TR/2011/WD-html5-author-20110809/the-samp-element.html
Wish they would redesign and reformat their documentation, it's such a mess.

**Comment by chris-morgan** [comment]
@DiemenDesign: incidentally, that document is thoroughly obsolete (though it hasn’t changed terribly much since then). https://html.spec.whatwg.org/#the-samp-element is the current spec. Remember also that most of the specification is intended for implementers (browsers, *&c.*) rather than authors (yeah, even when looking at the authors edition of the spec which shifts the balance a little). With that understanding, I see no mess at all. MDN is agreed upon by browser makers as the canonical (though non-normative) source of information for document authors; see https://developer.mozilla.org/en/docs/Web/HTML/Element/samp.

**Comment by andybrewer** [comment]
Thank you @chris-morgan - just implemented this in v1.1
