### ISSUE TITLE
Incorrect right margin on home page in Firefox Android

### ISSUE THREAD

**Issue by pranabekka** [andybrewer/mvp#105]
![Screenshot_2023-07-29-12-41-19-89_fd7367fd0afc7e864f00091a00b3d0b0](https://github.com/andybrewer/mvp/assets/20282735/399e39c7-7bc5-4471-9a3d-446ac185ebbb)

The second last horizontal rule is extending past the (intended) right margin of the page on mobile. I've zoomed out here on Firefox Focus (Android) to show it more clearly, but otherwise it creates horizontal scrolling that doesn't reveal any new content. Everything else has the correct right margin.

Issue does not occur in Chrome, but persists in full version of Firefox Android.

I guess it's mostly a non-issue, especially for an MVP.

**Comment by pranabekka** [comment]
Full support isn't necessary for an MVP. Additionally, Chrome is the primary browser on Android. The additional support would be an unecessary burden. 

My bad for opening an issue on a hair trigger :p

**Comment by pranabekka** [comment]
Closing as not planned

**Comment by ChristopherBilg** [comment]
I don't mind having this re-opened if you can show me the code that produced that screenshot and I'll look into it.

**Comment by pranabekka** [comment]
Inspecting it on Firefox for Linux (in responsive view), it seems like it's the border of the form that's doing it, or maybe the drop shadow, but the issue doesn't actually occur there, so I can't say for sure.

```
form {
    border: 1px solid var(--color-bg-secondary);
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow) var(--color-shadow);
    display: block;
    max-width: var(--width-card-wide);
    min-width: var(--width-card);
    padding: 1.5rem;
    text-align: var(--justify-normal);
}
```

**Comment by ChristopherBilg** [comment]
Very interesting. Thank you! I'll take a look tomorrow (Monday July 31st) and see if I can reproduce and if so maybe find a fix. I think I see what you mean so hopefully it's a quick find and fix.
