### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by diomed** [andybrewer/mvp#106]
mvp could improve by adding dark version of theme. 

since switching from light to dark is extremely popular nowadays.

**Comment by andybrewer** [comment]
You can implement dark mode by adding `<html color-mode="user">`

More info is available here: https://andybrewer.github.io/mvp/#faq `How do I handle a user's dark mode preference?`

You can edit/overwrite the dark mode styles here: https://github.com/andybrewer/mvp/blob/master/mvp.css#L28-L41

**Comment by diomed** [comment]
right
there should actually be toggle on the page then. for switching between them.

**Comment by diomed** [comment]
@ChristopherBilg could you possibly make a switcher based on this?
https://codepen.io/andy-set-studio/pen/VOELMZ

**Comment by ChristopherBilg** [comment]
Assuming you mean that JavaScript toggle, then no, because this is a CSS-only stylesheet and adding in additional JS (really any JS) shouldn't be necessary for an MVP.
