### ISSUE TITLE
modern css reset

### ISSUE THREAD

**Issue by diomed** [andybrewer/mvp#108]
hello

I suggest looking into this and adopting these practices:

https://andy-bell.co.uk/a-more-modern-css-reset/

**Comment by ChristopherBilg** [comment]
Is there any part, specifically, of MVP.css that you think is not well covered that additional styles would aid with?

**Comment by diomed** [comment]
text- balance on h elements is not covered and it should be, because it's new

**Comment by ChristopherBilg** [comment]
I'm going to wait on `text-balance` for now as it's still undergoing development for full support from top browsers. [See here.](https://caniuse.com/?search=text-balance) Do you have any other examples apart from `text-balance`?

**Comment by diomed** [comment]
man, this css reset was written by probably one of the best professionals in web design industry.
I'm not saying to copy-paste, I'm saying - here's something worth looking at , and if you choose to 
learn from it and implement some of it , cool. It's a suggestion on how to possibly better your css file. 
If you wanna take something from it, great, if not, that's your choice. 

I'm just giving you tips here on what I found you might use.

**Comment by ChristopherBilg** [comment]
Totally, I absolutely appreciate that. Let me give it a day or two to read over a couple times and let it cement in and I'll comment back on this thread.

**Comment by ChristopherBilg** [comment]
For now, I think we're good without any modifications unless specific code changes are implemented in a PR and we can show how they perform on various devices and browsers.

**Comment by diomed** [comment]
you should include text-balance at least since both firefox and chrome support it.
and safari is new IE anyway, in terms of lacking support.
