### ISSUE TITLE
proposal: make table headers sticky by default

### ISSUE THREAD

**Issue by komuw** [andybrewer/mvp#113]
- https://btxx.org/posts/Please_Make_Your_Table_Headings_Sticky/

```css
position: sticky;
top: 0;
```

**Comment by ChristopherBilg** [comment]
I'm hesitant to make this the default behavior as I am unsure if an MVP _really_ calls for it. I am however open to it if you can create a PR with the changes and possibly an example in the `mvp.html` file.

**Comment by michealp-coder** [comment]
My unsolicited comments: this seems like an appropriate _user override_ (not part of the core MVP.css functionality).
