### ISSUE TITLE
how to do drop down 4 level deep sub menu items' navbar?

### ISSUE THREAD

**Issue by sprappcom** [andybrewer/mvp#118]
possible to add navbar up to 4 levels deep?

**Comment by ChristopherBilg** [comment]
Sorry, I'm not sure if I understand your question. Can you be a little bit more specific?

**Comment by sprappcom** [comment]
@ChristopherBilg like the multilevel dropdown
https://bootstrap-menu.com/demos/multilevel.html#

**Comment by ChristopherBilg** [comment]
I see. Submenus like this are not currently implemented; however, if you'd like the generalize the CSS to allow for nested `<ul>` and `<ol>` elements inside of a `<li>` element, then I'd be happy to review it and add it in!

**Comment by ChristopherBilg** [comment]
Closing for now. Feel free to re-open with an associated PR.
