### ISSUE TITLE
W3C validations and Responsive images

### ISSUE THREAD

**Issue by badcat** [andybrewer/mvp#12]
Hi there.. Love this. Nice and Simple.  Thanks!
I made some W3C validation corrections like alt tags, nested ULs etc. in the HTML files and also added a new class so we could get responsive images in figure without adding widths on the img element.  Also added a changelog :). Consider a pull request? 
https://github.com/badcat/mvp

**Comment by andybrewer** [comment]
Thanks! I'll make these updates in the next release, minus the class recommendation. I'll keep this as a no-class stylesheet even if it requires some styling inside of HTML, which I think is OK for an MVP.

**Comment by badcat** [comment]
ok.. understood.  I thought HTML5 cannot use something like `width="100%"` though, which is why I'd added that. thanks again!

**Comment by badcat** [comment]
LOL - I'm a non-contributor. ok

**Comment by andybrewer** [comment]
Yeah, I removed that `width="100%"`. The contributors list is for those that submitted code to the MVP.css file itself. Thank you for bringing my attention to the HTML validation though -- much appreciated!

**Comment by badcat** [comment]
I was just ribbing you.  no worries. 👍
