### ISSUE TITLE
github-pages needs redeployed

### ISSUE THREAD

**Issue by thrivingproject** [andybrewer/mvp#121]
The site still has the old stylesheet which lacks the fix from https://github.com/andybrewer/mvp/pull/119. The fix added a missing comma that's needed to set the width of `textarea` elements. The site was last deployed before that fix, so when users download `mvp.css` from the site they get the old stylesheet, which is missing the comma.

**Comment by ChristopherBilg** [comment]
@andybrewer 

edit: v1.16 has been updated in the repository and just needs to be deployed.

**Comment by andybrewer** [comment]
Thanks! I redeployed the site and it's pulling in v1.16 now.

Also, I created a release here: https://github.com/andybrewer/mvp/releases/tag/v1.16 but feel free to edit as you see fit

**Comment by andybrewer** [comment]
Also, I updated the README.md to remove the release notes and contributors since GitHub has those featured in the sidebar now. I also removed the showcase because of the potential for dead links and folks switching to a different stylesheet.
