### ISSUE TITLE
404

### ISSUE THREAD

**Issue by ghost** [andybrewer/mvp#13]
https://andybrewer.github.io/mvp/#docs

Under HTML Reference,
`For a showcase of each styled element, check out the quickstart template ↗`

where `quickstart template ↗` leads to 404

**Comment by andybrewer** [comment]
It successfully downloads `mvp.html` for me. Are you still getting an error?

**Comment by hudsantos** [comment]
FYI
Here it is also downloading fine. It's ok.

**Comment by andybrewer** [comment]
Thanks @hudsantos !
