### ISSUE TITLE
Use of <aside> is problematic

### ISSUE THREAD

**Issue by chris-morgan** [andybrewer/mvp#2]
Using `<aside>` for cards is problematic. `<aside>` semantics are for optional extras, and tooling may be inclined to skip it altogether, or suggest to users that they can just skip it and go on to something else.

`<section><section>` would be tolerable to indicate this, if you’re *really* averse to the `class` attribute. But `class=card` is quite warranted, I’d say.

**Comment by philp** [comment]
I think that the styling here may look card-like, but semantically, these portions are still intended to be indirectly related to the main content. An aside doesn't necessarily imply that it's a sidebar or a call-out box. Remember this is MVP: it gets the job done, and in a nice way. I'd say stick with `<aside>` for now because it's semantically valid.

**Comment by andybrewer** [comment]
I'm inclined to agree w/ @philp on this one. I'd also like to stick to the "no classes" convention.

Here's Mozilla's take on `<aside>`: The HTML `<aside>` element represents a portion of a document whose content is only indirectly related to the document's main content. Asides are frequently presented as sidebars or call-out boxes.

I consider cards to be "call out boxes".

@chris-morgan What do you mean by "tooling may be inclined to skip it altogether", a screen reader?

**Comment by chris-morgan** [comment]
These cards seem to me to be part of the main content, not supplementary content.

By tooling I *mostly* mean screen readers. Default configurations of screen readers won’t skip asides when going through the document in order, but some configurations may skip things like that especially when navigating by landmark.

**Comment by andybrewer** [comment]
OK, thanks for clarifying. I'm going to leave as-is for now, but open to revisiting in the future if there's a semantic way to designate a card without a CSS class.

**Comment by iiic** [comment]
So if `aside` is problematic and this project stands on "no class" convention, what about using `role="grid"` `role="row"` & `role="cell"` … ? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Row_Role (nice html summary example snippet)

Advantage is it's standardized, working with assistive technologies and its universal

but it also have disadvantages … it cannot be used on most elements (semantic elements) and it's a bit difficult to understand structure (maybe only for me).

**Comment by DennisSuitters** [comment]
The problematic part comes down to the cards should be using `<article/>` with possible `<aside/>` as a child, or adjacent like a side informational panel or advertisement.
