### ISSUE TITLE
Some elements not styled

### ISSUE THREAD

**Issue by DennisSuitters** [andybrewer/mvp#22]
Hi Andy, I noticed that some elements are not covered, as in styled. Is this intentional to leave that up to the browser, or you've just not gotten too yet?

I guess if others see this issue, and are wondering what elements are available I suggest http://html5doctor.com/ as an easy to lookup site for the elements.

Do you need more help to do these Andy? I'm happy to contribute as time permits to add to your great repo. I've seen other minimalist css repo's similar to this one, but I didn't like the styling they used.

**Comment by andybrewer** [comment]
@DiemenDesign which tags are unstyled? Some like `div` are intentionally unstyled and some like `mark` intentionally use the default browser styling but I'd be interested in seeing any that are unstyled that you think could use styling.

**Comment by DennisSuitters** [comment]
`<address>` was one that comes to mind, mainly due to having to style it for my own use.

**Comment by andybrewer** [comment]
I considered that one too, but want sure how to style it. Can I see an
example of what you did?

**Comment by DennisSuitters** [comment]
`<dialog/>` which isn't mentioned on the html5doctor, but is here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog is another that comes to mind that might be something a lot of people use.

The `<address/>` element I don't have a specific style for, other than a lot of designers may use it in a header or footer for that sort of specific information. I know with using schema there is examples which also use elements such as `<span/>` that contain classes with the type of data like `tel` or `email`. But that's then getting back to classes again, I think they are more so scrappers/robots looking for data where pages don't specifically use meta schema or json-ld type data structures then look for information with the class names. I'll have a play around, and present some idea's.

Thank you for being open to idea's I find so many developers are of a rigid mindset and their way is the only way.

**Comment by DennisSuitters** [comment]
This https://developer.mozilla.org/en-US/docs/Web/HTML/Element resource seems to have a more concise list of elements.

**Comment by andybrewer** [comment]
Thanks @DiemenDesign, now I remember. I looked into `<dialog>`, but it's not supported by Safari yet. It's a top candidate to get styled once it is though. I'll close for now, but if you or someone else comes across this in the future when Safari does offer support, please let me know. Thanks!

**Comment by DennisSuitters** [comment]
No worries, it often baffles me how far behind Safari can be considering it uses -webkit as it's rendering engine.

**Comment by sukima** [comment]
Safari supports `<dialog>` as of May 2022 [per caniuse](https://caniuse.com/dialog). Can we reconsider styling it now?

**Comment by andybrewer** [comment]
Yes, I'll work on styling `<dialog>`, thanks for staying up to date on this!

**Comment by andybrewer** [comment]
The `<dialog>` element is now styled in the latest release: https://github.com/andybrewer/mvp/releases/tag/v1.11
