### ISSUE TITLE
Question about colors

### ISSUE THREAD

**Issue by schmanat** [andybrewer/mvp#28]
Hi 

First of all thx for this project, its pretty cool. But know I have a stupid questin. You defined color as var. But why you are using HEX Colors with 8 signs. I thougth a color definition as hex could only be 6 sign.

Whats color should be (i.e.) color-accent? The Google Chrome Dev Tools show me as color transparent

**Comment by andybrewer** [comment]
@schmanat Good question, this was new to me as well. I was looking for a way to automatically generate complimentary colors and found out that CSS allows for 8-digit hex values with the last 2 digits representing the opacity of the color. Here's a good walk through: https://alligator.io/css/hex-code-colors-alpha-values/
