### ISSUE TITLE
Any plans for and NPM package?

### ISSUE THREAD

**Issue by shawn-sandy** [andybrewer/mvp#30]
First of all, thank you and congrats this is Awesome!!! 

Do you have any plans for creating an NPM release would make updating and tracking way easier than cloning/forking?

Thanks
- Shawn

**Comment by andybrewer** [comment]
Thanks @shawn-sandy! Curious, what's the process for implementing an NPM release? Is it something you'd be able to help with or do I need to do it?

**Comment by shawn-sandy** [comment]
I would love to help, but it's pretty simple actually:
- Install npm you probably have this already if not check this link https://www.npmjs.com/get-npm
- In the MVP folder root run, `npm init` from the command line
- You get some interactive prompts, answer them accordingly and it generates an npm package.json
- Register and publish to npm - https://docs.npmjs.com/creating-and-publishing-scoped-public-packages
- That's it :)

Here is a good read https://www.freecodecamp.org/news/how-to-make-a-beautiful-tiny-npm-package-and-publish-it-2881d4307f78/

Let me know if you need help...

Regards
~Shawn

**Comment by andybrewer** [comment]
Thanks @shawn-sandy! It's now listed as an NPM package here:
NPM: https://www.npmjs.com/package/mvp.css
Unpkg: https://unpkg.com/mvp.css
