### ISSUE TITLE
HEX8 to var ref?

### ISSUE THREAD

**Issue by badcat** [andybrewer/mvp#34]
I was looking at this issue re: HEX8 colors. https://github.com/andybrewer/mvp/issues/28  I wished currentColor could be used somehow...

And as much as I think HEX8 colors are cool, I can never remember the correct hex for a specific alpha percentage. Just using  .8  as the % is easier for me.

So what if the HEX8 color was swapped with a variable reference Base color for RGBA allowing the color to be set in one variable and then just change the alpha?

```
:root {
  /* #118BEE in decimal RGB converts to... 17, 139, 238 */
    --color-secondary-base: 17, 139, 238;

  /* Call color-secondary-base as a variable  inside the rbga value, set alpha to 1 */
    --color-secondary: rgba(var(--color-secondary-base), 1);

  /* Accent color is now tied back to the base color allowing a lighter alpha value*/
    --color-secondary-accent: rgba(var(--color-secondary-base), 0.15);
 }
```
 
Kinda like this...  **https://codepen.io/badcat/pen/MWapwMZ**
Allowing the accent color to be coupled to the secondary etc...
<img width="165" alt="currentcolor-no" src="https://user-images.githubusercontent.com/26096/80172465-10798780-85bb-11ea-92ca-ca6ca11b52db.png">

**Comment by andybrewer** [comment]
Thanks @badcat, I thought about this approach, but it seemed to me that most designers use hex colors rather than RGB, so I opted to stick with hex8. I agree that it does come at a cost of more difficult base16 calculations though for the alpha values.

For those coming here unfamiliar with hex8 there's a good tutorial here: https://css-tricks.com/8-digit-hex-codes/

**Comment by badcat** [comment]
Hmm maybe. 🤔 I have to wonder, when we finally get more support for extended RGB gamuts, if HEX8 will die off. Couple that with new/upcoming browser support for display-P3 and LCH - all of these are way easier to remember using alpha percentages as compared to the 100 value conversion chart for Hex alpha. 🖍 _Quick..._ what's 25% alpha in hex. It's 40 of course. LOL.
