### ISSUE TITLE
Problem with hidden

### ISSUE THREAD

**Issue by GrosSacASac** [andybrewer/mvp#35]
Thank you for this amazing css I love it.

There is a small issue with the html hidden attribute. When used on a form it is override by display: flex.

Temporary fix: add
[hidden] {
    display: none !important;
}
in CSS

**Comment by iiic** [comment]
… or when used on `HTMLLinkElement` (`a`) its overriden by `display: inline-block;`

**Comment by andybrewer** [comment]
Thanks @GrosSacASac and good catch!

The use cases I tested: `<p hidden>`, `<a hidden>` and `<section hidden>` appear to be hidden successfully without `!important`, but I will add `display: none` to the next version. If you know of use cases where it's still visible without `!important`, please let me know. Thanks!
