### ISSUE TITLE
cannot use tabs for ident code snippet

### ISSUE THREAD

**Issue by iiic** [andybrewer/mvp#36]
Don't know if bug or feature, but why it's there `white-space: pre-line;` on `pre` element?

( https://github.com/andybrewer/mvp/blob/566a4242b998cb818a6b859f68828c1d78b7d245/mvp.css#L217 )

With that i cannot format code snippet like this:

``` javascript
( () =>
{
	let counter = ( a, b ) =>
	{
		return a + b;
	}
} )();
```

and always got only:

``` javascript
( () =>
{
let counter = ( a, b ) =>
{
return a + b;
}
} )();

```

**Comment by andybrewer** [comment]
@iiic Thank you!! This has been a tricky one to get just right, but I think the next version will fix this. Much appreciated :)
