### ISSUE TITLE
Auto margin with wide table

### ISSUE THREAD

**Issue by ope-nz** [andybrewer/mvp#39]
Just like to point out that very wide tables arent working nicely with the auto margin-left and margin-right. The table creeps across the page the wider it is. Example below.

![image](https://user-images.githubusercontent.com/26259049/80321495-8f97e580-8871-11ea-99d7-ac46d2d97652.png)

**Comment by andybrewer** [comment]
Thanks @ope-nz ! Tables have been tricky to style, but I'm hoping this next release provides better styling. In your use case, it should hopefully not overflow the container and instead should provide a horizontal scrollbar if necessary.
