### ISSUE TITLE
Use unitless line height

### ISSUE THREAD

**Issue by BinaryMoon** [andybrewer/mvp#40]
Hi - I like the idea of mvp.css. Thanks for the work so far!

I tried using it on a test site and found a problem with the default line-heights so I thought I would let you know.

Essentially the 150% height doesn't work consistently for all font sizes. If you change the font size to something larger the line height does not scale relative to the font. If you use unitless font sizes you will get the same effect but the text will not overlap.

Swapping from 150% to 1.5 achieves the same effect but makes the text readable everywhere.

No worries if you're not interested. Just thought I'd let you know in case.

**Comment by andybrewer** [comment]
@BinaryMoon - Thanks! I did a small cursory test and couldn't tell the different between `line-height: 150%` and `line-height: 1.5` when modifying body font sizes. However, I'll updated it to `1.5` in the next release as they look equivalent on my end and sounds like might help in your use case.
