### ISSUE TITLE
Consider using .editorconfig

### ISSUE THREAD

**Issue by iiic** [andybrewer/mvp#42]
Have you considered using .editorconfig file?

It's small file which sets editor (and github) behaviour for easier contributing in project.

Like this ( https://github.com/airbnb/javascript/blob/master/.editorconfig ). Docs -> https://editorconfig.org/

**Comment by andybrewer** [comment]
@iiic Thanks for the suggestion. I'm not sure that we currently need it as it's a tiny project and I haven't seen any issues with PR formatting yet. Thanks for the suggestion though.
