### ISSUE TITLE
Add "white-space: nowrap;" to "nav ul li ul" section

### ISSUE THREAD

**Issue by ctp52** [andybrewer/mvp#43]
Double word pulldown menu items break at the end of the first word.
e.g.
```Contact Us```
becomes
```
Contact
Us
```

unless "white-space: nowrap;" is added the menu pulldown "nav ul li ul".

**Comment by DennisSuitters** [comment]
@ctp52 is correct, I added this to my stylesheet after my initial PR, forgot about it later.

**Comment by andybrewer** [comment]
Good catch! Just updated it. Thanks :)
