### ISSUE TITLE
Fix nav menu at top of window

### ISSUE THREAD

**Issue by ctp52** [andybrewer/mvp#44]
Long pages scroll the nav menu off the top of the page. Sometimes it is preferred to fix the menu at the top of page and let content scroll past/underneath it. The following additions to the "nav" entry will enable this:
```
  position: fixed;
  top: 0;
  z-index: 30;
```
It could be left as a comment in the css rather than imposing on all naive users. The "margin-bottom : 7rem" might be revised if the menu is fixed. Other page content must start below the height of the menu or the first line(s) will be hidden.

**Comment by andybrewer** [comment]
Thanks! I think I'll leave it out for the time being as I could go down the rabbit hole of commented out styling variations, but thanks for posting the code here for anyone that wants to implement it.
