### ISSUE TITLE
Nicer form elements

### ISSUE THREAD

**Issue by constructit** [andybrewer/mvp#45]
You can present inputs, textareas and selects a bit nicer by having them take full width.

```
input,
label,
select,
textarea {
    display: block;
    font-size: inherit;
    max-width: var(--width-card-wide);
    width: 100%;
    box-sizing: border-box;
}

input[type="checkbox"],
input[type="radio"] {
    display: inline-block;
    width: auto;
}
```

![image](https://user-images.githubusercontent.com/6616690/82194513-3a427780-98f7-11ea-85a4-f0c83ff5fc1e.png)

**Comment by andybrewer** [comment]
Thanks! I've been debating styling the `select` dropdown and this would be a nice touch to include with that update. I noticed the screenshot has a white background on the select field. If that's custom styling and you'd like to submit a PR with this `max-width` update as well I'd be happy to review it.

**Comment by andybrewer** [comment]
I'm happy to review a PR, but I'll close this issue for now as the elements seem respectable enough for an MVP. Thanks.
