### ISSUE TITLE
[DOCS] Improve HTML elements/tags documentation

### ISSUE THREAD

**Issue by Israel-Laguan** [andybrewer/mvp#46]
# Rationale

One of the most important part of any modern documentation are code examples. I understand this project don't need too much code on top of normal HTML tags, but most of the target users are in need or simple used to see some code examples to copy/paste, and maybe some ready made layouts/"component" to use.

# Request

- [ ] Create a better "Examples" section by adding more use cases
- [ ] Add examples with basic css style, maybe inlined,  maybe using `<style>` tags.
- [ ] Mimic some basic layouts and components (for example Card, Dropdown, Navbar, Sidebar, etc.) using MVP.css and maybe some basic CSS in a "copy/paste" way.

# Proposal

I can contribute with some code examples.

**Comment by andybrewer** [comment]
I'll close this issue, but please feel free to send a PR with suggested examples.
