### ISSUE TITLE
Congrats (& a suggestion)

### ISSUE THREAD

**Issue by fevangelou** [andybrewer/mvp#5]
@andybrewer Your approach is smart and the HTML is a breeze to read. What a fresh change from the class-itis of frameworks like Tailwind!

Although the targeting is MVPs as you also mention on the site, it could *possibly* evolve to a very powerful HTML/CSS framework, far more than setting up a MVP :)

What I'd like to throw in as an idea is that in a future v2 of mvp.css you could consider using custom HTML tags to allow for inserting new tags in the mix for better positioning/layout, typography and more.

A simple example could be:
```
<m-grid>
    <m-cell></m-cell>
    <m-cell></m-cell>
    <m-cell></m-cell>
</m-grid>
```
(using "m" as the prefix for mvp.css and in order to be somewhat future-proof for possible HTML tag additions, but also web component/JS friendly).

Again, this is just an idea. If anyone's to learn 200 CSS classes to use something like Tailwind (et al), they might as well learn custom (prefixed) HTML tags that potentially make more sense.

And as for search engines, technically speaking it doesn't matter to them if you use custom HTML. SEO-wise, if one wants to be Google-friendly, it's either way preferable to use structured data over semantic HTML.

_(I also posted this on HN but quickly realized it'd be better to post here...)_

**Comment by andybrewer** [comment]
I thought about this, but it would break the "add and forget" kind of simplicity I was going for. Basically, replacing CSS classes with custom HTML tags.
