### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by jpic** [andybrewer/mvp#54]
Hi all,

Thank you for sharing this great code!!

Is there any known way to make IE11 work ? Polyfills maybe ?

Thank you!

**Comment by andybrewer** [comment]
Thanks @jpic! For me, IE 11 is beyond the scope of what I'd like this stylesheet to do. I typically use MVP.css to get an idea launched for 3-6 months knowing I'll replace it with a custom design down the road. Until then, I'm OK if a small percent of users experience UI bugs.
