### ISSUE TITLE
Include some sort of showcase list

### ISSUE THREAD

**Issue by brunoluiz** [andybrewer/mvp#55]
I find this framework quite cool, but I really wished there was some showcase section on the landing page or readme. It would be interesting to see how it goes out in the wild and how people customize it 😉

**Comment by andybrewer** [comment]
Absolutely! After the holidays I'll go about setting that up.

**Comment by andybrewer** [comment]
It's up here: https://github.com/andybrewer/mvp#showcase

Feel free to create a PR with any more you'd like to see on there
