### ISSUE TITLE
Implement semantic role attribute

### ISSUE THREAD

**Issue by mildred** [andybrewer/mvp#56]
The role attribute allows to have semantic markup but with greater expressiveness. For example a button can be marked with `role="link"` in case we want to show a link but need a form to make a POST request. Also, the `role="none"` or `role="presentation"`  can be used to remove the semantic meaning of an element.

See :

- https://w3c.github.io/using-aria/
- https://www.w3.org/TR/wai-aria/#roles_categorization

**Comment by andybrewer** [comment]
Yes, it's true that it could be used (and should be for accessibility), but I'm not sure we want to tie styling to those attributes since it expands the numbers of things a UI designer would have to remember to get an MVP shipped.
