### ISSUE TITLE
In Sections, justify-content: center clips content on small screens

### ISSUE THREAD

**Issue by ScottGuthart** [andybrewer/mvp#57]
In sections, using `justify-content: center;` will clip content if your screen isn't wide enough. 

Andy, I'm not sure if this is necessarily an issue given the MVP ethos of this project but I just wanted to mention it.

It came up for me when placing a code block in a section and then loading up the page on my phone.

**Comment by andybrewer** [comment]
Do you have some examples?

**Comment by ScottGuthart** [comment]
Sure, [here's one](https://codesandbox.io/s/mvpcss-section-clipping-17n8q?resolutionWidth=320&resolutionHeight=675&file=/index.html).

Maybe there's something I'm missing.

**Comment by andybrewer** [comment]
Thanks! I see the problem you're describing. I tried messing around with a few ways to fix it without altering the `display: flex;` and `justify-content: center` of the parent `section` tag, but couldn't find anything simple that would do the trick. I supposed I could add a few media queries to handle this use case, but that's ultimately an imperfect solution as there are many different device sizes. Do you happen to have a solution that you think might work more universally than media queries?

**Comment by ScottGuthart** [comment]
Maybe something like this? 

```css
section * {
  overflow: auto;
}
```

I [updated](https://codesandbox.io/s/mvpcss-section-clipping-17n8q?resolutionWidth=320&resolutionHeight=675&file=/index.html) that earlier example to test it out, and it seems to work okay. Maybe there are downsides I'm not thinking of?

**Comment by andybrewer** [comment]
Thanks! Fixed here: https://github.com/andybrewer/mvp/releases/tag/v1.7

**Comment by ctp52** [comment]
The "section * { overflow: auto; }" fix hides the numbers in \<ol>\<li>some text\</li>\</ol>
I needed to add a qualifier statement in my custom.css that follows mvp.css:

  section li { overflow: visible; }

to fix it.

**Comment by andybrewer** [comment]
Good catch! Fixed in v1.7.1 which was just published.
