### ISSUE TITLE
Question on <a> usage

### ISSUE THREAD

**Issue by slamethendry** [andybrewer/mvp#58]
First off, thanks for mvp.css.

My a tag for link looks different in different browser.  Normal in Safari, but in Firefox and Chrome, the link is elevated.  So in the example below, the "here" is higher than the rest of the sentence if viewed in FF/Chrome.

Click <a href="https://andybrewer.github.io/mvp/">here</a> to read about mvp.css.

Any insight to what I did wrong?  Thanks.

**Comment by andybrewer** [comment]
Can you share your code on codepen.io or a similar code sharing site?

**Comment by slamethendry** [comment]
As I was going to share the code, I tried re-creating the offending code and I switched to using the css file in unpkg.com.  And the issue disappeared.

So I re-copied mvp.css to my local and the problem disappeared also.  Not sure why the first file had issue.  (Even weirder, Safari had no issue the whole time.)

User error.  Thanks for helping!
