### ISSUE TITLE
Strange alignment of checkbox and radio inputs

### ISSUE THREAD

**Issue by zgoda** [andybrewer/mvp#59]
In both Chrome and Firefox checkbox and radio inputs are strangely aligned relative to their labels.

Chrome 90:

![Zrzut ekranu z 2021-04-23 23-43-50](https://user-images.githubusercontent.com/141999/115932938-41babb00-a48e-11eb-9182-74fd7aa45661.png)

Firefox 87:

![Zrzut ekranu z 2021-04-23 23-45-11](https://user-images.githubusercontent.com/141999/115932959-4bdcb980-a48e-11eb-873e-06abc0289a7f.png)

**Comment by andybrewer** [comment]
I'm not seeing that misalignment on the form on the project homepage: https://andybrewer.github.io/mvp/ Are you?

Feel free to share your code on codepen.io or a similar site where you're able to reproduce the bug. Thanks.

**Comment by zgoda** [comment]
Heh, now it looks fine.

![Zrzut ekranu z 2021-04-25 19-23-49](https://user-images.githubusercontent.com/141999/116002833-cb3bcb80-a5fb-11eb-997c-c88d154a7beb.png)
