### ISSUE TITLE
Non-semantic labels require IDs & yield minimum target size

### ISSUE THREAD

**Issue by coolaj86** [andybrewer/mvp#67]
In the example you’re using non-semantic labels that require IDs. Why not use them in the traditional fashion?

```html
<label>Name: 
<input type="text"></label>
```

This also has the benefit of allowing you to observe Fitt’s Law and  control the target size of the element perfectly.

**Comment by andybrewer** [comment]
Sorry, but can you please clarify which code you're referring to?
