### ISSUE TITLE
Misbehaviour with a standard example page

### ISSUE THREAD

**Issue by ctp52** [andybrewer/mvp#74]
I recently discovered [https://dohliam.github.io/dropin-minimal-css/] a site that displays a standard example web page using 140 selectable no-class CSS libraries. mvp is included in the top pull-down list and misbehaves when article tags are within section tags.

The fix in version 1.8 is to change the section definition from:
`    section {
        display: flex;
        flex-wrap: wrap;
        justify-content: var(--justify-important);
    }`
to:
`    section {
        display: block;
        flex-wrap: wrap;
        justify-content: var(--justify-important);
    }`
I can foresee that this change might have other effects not considered during my testing but it does make a major difference on this web page.

**Comment by andybrewer** [comment]
I don't think I'll fix this one. `<section>` and `<article>` are used as same-level elements in MVP, rather than nested elements.
