### ISSUE TITLE
Maybe don't suggest exactly copies of companies

### ISSUE THREAD

**Issue by augustobmoura** [andybrewer/mvp#8]
![image](https://user-images.githubusercontent.com/5845160/77553987-43354080-6e94-11ea-9476-0d09ffc58ac8.png)
Shouldn't this just mean Paypal?
I mean, is still a valid idea...

**Comment by ChristopherBilg** [comment]
Also, PayPal was co-founded by Elon Musk. The same Elon Musk that has plenty of technical and, as you say, "programming" experience.

**Comment by AxelTheGerman** [comment]
Nice little project, hope comments/issues like this, that don't add too much value and sounds like having a bit of a negative undertone, don't cost too much of your time that could go to improving the product or living your life

**Comment by philp** [comment]
Yeah, agree. Maybe needs some reasoning to be a valid issue?

Good work, man.

**Comment by andybrewer** [comment]
"PayPal for banking" -- genius!
