### ISSUE TITLE
How to make input width same as the card container

### ISSUE THREAD

**Issue by zemian** [andybrewer/mvp#81]
Hi, I am trying make the input width same width as the card container. Looking at the example: https://andybrewer.github.io/mvp/mvp.html, the input width has `size="20"`, but if I remove it, and add `style="width: 100%;"`, it will not aligned correctly. Is there a quick way to do this?

Thanks!

**Comment by andybrewer** [comment]
I just tried in Chrome and `style="width: 100%;"` does increase the width of the `input` for me.

<img width="957" alt="Screen Shot 2022-09-12 at 8 34 33 AM" src="https://user-images.githubusercontent.com/7093/189695677-e2e2287c-5a99-470f-aeff-c78d05555314.png">

**Comment by andybrewer** [comment]
Oh, I misread your comment. I see how it's not aligned.

You could use `style="width: calc(100% - 1.6rem);"`

`<input>` has 0.8 rem left & right padding.

<img width="853" alt="Screen Shot 2022-09-12 at 8 37 46 AM" src="https://user-images.githubusercontent.com/7093/189696428-633925c0-27c3-46c8-90ad-a6993c51dd0c.png">

**Comment by zemian** [comment]
Okay, thanks for the workaround Andy! It would be nicer to not have to do that explicitly. But I guess we can't have everything. :)

Cheers!

**Comment by andybrewer** [comment]
Actually, I think you're right! I've updated it here: https://github.com/andybrewer/mvp/releases/tag/v1.10.1
