### ISSUE TITLE
Unused empty space ?

### ISSUE THREAD

**Issue by devnewton** [andybrewer/mvp#84]
How to avoid having a large empty space between header and main content ?

![image](https://user-images.githubusercontent.com/103828758/190103548-43d3a92e-11f5-4df1-865e-acd32398abb1.png)

**Comment by andybrewer** [comment]
That large space is by default. The `<nav>` tag has `margin-bottom: 7rem`: https://github.com/andybrewer/mvp/blob/master/mvp.css#L142

You can create a custom style like `<nav style="margin-bottom: 3rem">`, or overwrite the style globally by including your own CSS stylesheet where you define the `nav` style as you like.
