### ISSUE TITLE
mvp.css v1.13 Release

### ISSUE THREAD

**Issue by ChristopherBilg** [andybrewer/mvp#92]
Requesting a release for v1.13. If need be, let me know and I'll make a PR for all of the updates needed in this repo.

**Comment by diomed** [comment]
any plans on releasing next version that has scrollbars, for all?

**Comment by ChristopherBilg** [comment]
I don't have access to release versions. @andybrewer If I prepare a v1.13 release branch, would you be able to make a release?

**Comment by andybrewer** [comment]
Yes, no problem

**Comment by ChristopherBilg** [comment]
@diomed https://github.com/andybrewer/mvp/releases/tag/v1.13
