### ISSUE TITLE
mark

### ISSUE THREAD

**Issue by diomed** [andybrewer/mvp#93]
<mark> — text highlighting

it wold really be nice if mark was styled same as background for code or something similar

**Comment by ChristopherBilg** [comment]
Based on the MDN description of [`<mark>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark), I would actually think that keeping it how it is rendered now is ideal.

![image](https://github.com/andybrewer/mvp/assets/3654150/7a718ace-a1fc-44c9-879e-bcca70651b16)
