### ISSUE TITLE
thought on sup

### ISSUE THREAD

**Issue by diomed** [andybrewer/mvp#95]
raised text on notification bubbles

Idea is for it to be monospaced.

**Comment by ChristopherBilg** [comment]
Can you reword what the issue/feature request is?

**Comment by diomed** [comment]
it's an observation that if font was monospaced in notification bubbles, it might be easier to read.

**Comment by ChristopherBilg** [comment]
As is: ![image](https://github.com/andybrewer/mvp/assets/3654150/9ea00fbf-7d5c-41a7-9e80-5a1878af9ba3)
With a CSS Monospace Font Stack: ![image](https://github.com/andybrewer/mvp/assets/3654150/4f2de70d-7dab-46d8-b69d-849f04cb2b3d)

I'm open to this change, but I'm not especially convinced about it being easier to read. Thoughts?

**Comment by diomed** [comment]
actually it's ok the way it is.
