### ISSUE TITLE
chevron for summary

### ISSUE THREAD

**Issue by diomed** [andybrewer/mvp#96]
what do you think about adding custom chevron icon for summary

details :: summary

**Comment by ChristopherBilg** [comment]
I definitely think an argument can be made, what did you have in mind specifically to change on it?

**Comment by diomed** [comment]
to look like in this pen:
https://codepen.io/koca/pen/RyeLLV

maybe with icon?
I'm not so good in css tho

**Comment by ChristopherBilg** [comment]
The Chevron itself isn't directly modified in CSS in the same way as text colors, or marginal spacing are. We would be replacing the current icon with a new icon instead, and right now I don't think that's necessary for an MVP CSS framework.
